question_data = [

    {"""category""": """Entertainment: Television""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """AMC's "The Walking Dead", Rick, Carl, Daryl, Morgan, Carol and 
     Maggie were introduced to us in Season 1.""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """hard""",
     """question""": """In "The Sims" series, the most members in a household you can have is 8.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Geography""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """A group of islands is called an 'archipelago'.""", """correct_answer""": """True""",
     """incorrect_answers""": ["""False"""]},
    {"""category""": """History""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """The two atomic bombs dropped on Japan by the United States 
     in August 1945 were named 'Little Man' and 'Fat Boy'.""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """Entertainment: Film""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """Leonardo DiCaprio won an Oscar for Best Actor in 2004's "The Aviator".""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """General Knowledge""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """French is an official language in Canada.""", """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """History""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """The Spitfire originated from a racing plane.""", """correct_answer""": """True""",
     """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Music""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """The country song  (A Boy Named Sue) was written by Shel Silverstein.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """In "Team Fortress 2", the "Bill's Hat" is a reference to the game "Dota 2".""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """General Knowledge""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """Sitting for more than three hours a day can cut two years off a person's life expectancy.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """General Knowledge""", """type""": """boolean""", """difficulty""": """easy""", """question""": """Pluto is a planet.""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """In the game "Subnautica", a "Spadefish" will attack you.""",
     """correct_answer""": """False""", """incorrect_answers""": ["""True"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """Ana was added as a new hero for the game Overwatch on July 19th, 2016.""", """correct_answer""": """True""",
     """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Music""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """For his performance at ComplexCon 2016 in Long Beach, California, Skrillex 
     revived his "Mothership" set piece for one night only.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Sports""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Science & Nature""", """type""": """boolean""", """difficulty""": """hard""",
     """question""": """The value of one Calorie is different than the value of one calorie.""", """correct_answer""": """True""",
     """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """Several characters in "Super Mario 64" blink their eyes, including Mario himself.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Film""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """"Foodfight!" earned less than $80,000 at box office.""", """correct_answer""": """True""",
     """incorrect_answers""": ["""False"""]},
    {"""category""": """Science & Nature""", """type""": """boolean""", """difficulty""": """medium""",
     """question""": """"Tachycardia" or "Tachyarrhythmia" refers to a resting heart-rate near or over 100 BPM.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]},
    {"""category""": """Entertainment: Video Games""", """type""": """boolean""", """difficulty""": """easy""",
     """question""": """In the video game "Splatoon", the playable characters were originally going to be rabbits instead of squids.""",
     """correct_answer""": """True""", """incorrect_answers""": ["""False"""]}]
